# This configuration file is created for the cycle branch

Main:
    event_queue_size: 4096

EventSinks:
    #- LogEventSink:
    #    class: "log_event_sink.LogEventSink"
    - MQTTPublisher:
        class: "mqtt_event_sink.MQTTEventSink"
        hostname: "dime.smartamerica.io"
        #hostname: "m2m.eclipse.org"
        hostport: 1883
        username: null
        password: null
        keepalive: 60
    - MySQLDatabase:
        class: "mysql_event_sink.MySQLEventSink"
        dbname: "scale_cycle"
        username: "scale_usr"
        password: "123456"
    - MySQLDatabaseClassified:
        class: "mysql_classified_event_sink.MySQLClassifiedEventSink"
        dbname: "scale_cycle"
        username: "scale_usr"
        password: "123456"
        event_types:
            - "location_update"
            - "iwlist_scan"
    - RFWriter:
        class: "rf_event_sink.RFEventSink"
        tty_path: "/dev/rfcomm9"
        sleep: 0

Applications:
    - LocationManager:
        class: "location_manager.LocationManager"
        debug: true
    - MySQLDatabase:
        class: "mysql_maintainer.MySQLMaintainer"
        dbname: "scale_cycle"
        username: "scale_usr"
        password: "123456"
    - RFListener:
        class: "rf_listener.RFListener"
        tty_path: "/dev/rfcomm9"
    - GPSGeofence:
        class: "gps_geofence.GPSGeofence"
        config: "/etc/scale/client/cycle/targets.yml"
        debug: true

Sensors:
    - HBSensor:
        class: "heartbeat_virtual_sensor.HeartbeatVirtualSensor"
        dev_name: "hb0"
        interval: 60
    #- PIRSensor:
    #    class: "pir_virtual_sensor.PIRVirtualSensor"
    #    dev_name: "pir0"
    #    gpio_pin: 17
    #- LightSensor:
    #    class: "light_virtual_sensor.LightVirtualSensor"
    #    dev_name: "light0"
    #    analog_port: 3
    #    threshold: 400
    #- GasSensor:
    #    class: "gas_virtual_sensor.GasVirtualSensor"
    #    dev_name: "gas0"
    #    analog_port: 0 
    #    threshold: 500
    #- RawAnalogSensor:
    #    class: "raw_analog_virtual_sensor.RawAnalogVirtualSensor"
    #    dev_name: "raw0"
    #    analog_port: 2
    #- GeoIPSensor:
    #    class: "location_sensors.geo_ip_virtual_sensor.GeoIPVirtualSensor"
    #    dev_name: "geoip0"
    - InternetAccessSensor:
        class: "internet_access_virtual_sensor.InternetAccessVirtualSensor"
        dev_name: "net0"
    - IWListSensor:
        class: "iwlist_virtual_sensor.IWListVirtualSensor"
        dev_name: "iw0"
        if_name: "wlan0"
        debug: true
        empty_essid: false
        max_unknown: 0
        white_list:
            - "SCALE"
            - "THINGSTITUTE"
            - "MoCoDanHoffman"
            - "Peerless-2.4"
            - "MCGUEST"
            - "xfinitywifi"
            - "SCALE_VC"
            - "SCALE_VC_Guest"
            - "SubwayGuest"
            - "Dumplinghouse"
    - GPSSensor:
        class: "location_sensors.gps_virtual_sensor.GPSVirtualSensor"
        dev_name: "gps0"

