#This configuration spins up a client with dummy sensors and publishes via MQTT
# Ideal for testing on a laptop :)

EventSinks:
    - MQTTEventSink:
        class: "mqtt_event_sink.MQTTEventSink"
        hostname: "iqueue.ics.uci.edu"
        #hostname: "dime.smartamerica.io"
        #hostname: "m2m.eclipse.org"
        hostport: 1883
        username: null
        password: null
        keepalive: 60


Sensors:
    - DummyLightSensor:
        class: "dummy_sensors.dummy_light_virtual_sensor.DummyLightVirtualSensor"
        dev_name: "light0"
    - RPiMemorySensor:
        class: "diagnostic_sensors.ram_utilization_virtual_sensor.RAMUtilizationVirtualSensor"
        dev_name: "rpis0"
        interval: 30
